# Generated by Django 4.1.6 on 2023-02-08 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_myuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='username',
            field=models.CharField(default='taharqa', max_length=30),
            preserve_default=False,
        ),
    ]
