# Generated by Django 4.1.6 on 2023-02-16 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appalbums', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photos',
            name='photo_title',
            field=models.CharField(max_length=50),
        ),
    ]
