version: 2.1

jobs:
  test-and-lint:
    docker:
      - image: circleci/python:3.7-stretch-node-browsers
    steps:
      - checkout
      - run:
          name: install dependencies
          command: npm install
      - run:
          name: run tests
          command: npm run
      - run:
          name: create virtual env
          command: python -m venv venv
	  path: backend
      - run:
          name: install deps
          command: pip install -r requirements.txt
      - run:
          name: make migrations
          command: python manage.py makemigrations && python manage.py migrate
	  path: backend
      - run:
          name: runserver
          command: python manage.py runserver
	  path: backend

workflows:
  build-and-test-workflow:
    jobs:
      - test-and-lint