version: 2.1

jobs:
  test-and-lint:
    docker:
      - image: circleci/python:3.7-stretch-node-browsers
    steps:
      - checkout
      -run:
          name: update pip
	  command: pip install -U pip setuptools virtualenv
      - run:
          name: list directory
          command: cat backend/requirements.txt
      - run:
          name: create virtual env and activate
          command: cd backend && python -m venv venv && source venv/bin/activate
      - run:
          name: install deps
          command: pip install -r requirements.txt
      - run:
          name: make migrations
          command: python manage.py makemigrations && python manage.py migrate
      - run:
          name: runserver
          command: python manage.py runserver	  
      - run:
          name: install dependencies
          command: cd ../frontend/ && ls && npm install
      - run:
          name: run tests
          command: npm run



workflows:
  build-and-test-workflow:
    jobs:
      - test-and-lint