version: 2.1

jobs:
  test-and-lint:
    docker:
      - image: circleci/python:3.7-stretch-node-browsers
    steps:
      - checkout
      - run:
          name: install dependencies
          command: cd frontend && ls && npm install
      - run:
          name: run tests
          command: npm test
      - run:
          name: run app
          command: npm run build

workflows:
  build-and-test-workflow:
    jobs:
      - test-and-lint