version: 2.1

jobs:
  test-and-lint:
    docker:
      - image: circleci/python:3.7-stretch-node-browsers
    steps:
      - checkout
      - run:
          name: install dependencies
          command: cd frontend && npm install
      - run:
          name: run tests
          command: npm run
      - run:
          name: create virtual env
          command: cd && cd backend && python -m venv venv
      - run:
          name: install deps
          command: pip install -r requirements.txt
      - run:
          name: make migrations
          command: python manage.py makemigrations && python manage.py migrate
      - run:
          name: runserver
          command: python manage.py runserver


workflows:
  build-and-test-workflow:
    jobs:
      - test-and-lint